language: node_js
node_js:
  - "10.15.3"
install:
  - "npm install"
cache:
  directories:
  - "node_modules"
script:
  - npm run test
after_success: npm run coverage
branches:
  only:
    - develop
before_script:
- psql -c 'create database testdbname;’ -U postgres
services:
- postgresql     